CREATE TABLE GSU.PRINCIPALS
(
  OBJID                 VARCHAR2(32 BYTE)       NOT NULL,
  USERNAME              VARCHAR2(255 BYTE),
  PASSWORD              VARCHAR2(100 BYTE),
  EMAIL                 VARCHAR2(100 BYTE),
  GSM                   VARCHAR2(32 BYTE),
  TITLE                 VARCHAR2(32 BYTE),
  NAME                  VARCHAR2(32 BYTE),
  SURNAME               VARCHAR2(32 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX GSU.I_PRINCIPALS_OBJID ON GSU.PRINCIPALS
(OBJID)
LOGGING
NOPARALLEL;

ALTER TABLE GSU.PRINCIPALS ADD (
  PRIMARY KEY
  (OBJID)
  USING INDEX GSU.I_PRINCIPALS_OBJID
  ENABLE VALIDATE);

CREATE TABLE GSU.INGREDIENTS
(
  OBJID                 VARCHAR2(32 BYTE)       NOT NULL,
  TYPE                  VARCHAR2(255 BYTE),
  NAME                  VARCHAR2(100 BYTE),
  UNIT                  VARCHAR2(50 BYTE),
  AMOUNT                VARCHAR2(32 BYTE),
  PRINCIPAL_OID         VARCHAR2(32 BYTE)
  )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX GSU.I_INGREDIENTS_OBJID ON GSU.INGREDIENTS
(OBJID)
LOGGING
NOPARALLEL;

ALTER TABLE GSU.INGREDIENTS ADD (
  PRIMARY KEY
  (OBJID)
  USING INDEX GSU.I_INGREDIENTS_OBJID
  ENABLE VALIDATE);