CREATE TABLE GSU.PRINCIPALS
(
  OBJID                 VARCHAR2(32 BYTE)       NOT NULL,
  USERNAME              VARCHAR2(255 BYTE),
  PASSWORD              VARCHAR2(100 BYTE),
  EMAIL                 VARCHAR2(100 BYTE),
  GSM                   VARCHAR2(32 BYTE),
  TITLE                 VARCHAR2(32 BYTE),
  NAME                  VARCHAR2(32 BYTE),
  SURNAME               VARCHAR2(32 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX GSU.I_PRINCIPALS_OBJID ON GSU.PRINCIPALS
(OBJID)
LOGGING
NOPARALLEL;

ALTER TABLE GSU.PRINCIPALS ADD (
  PRIMARY KEY
  (OBJID)
  USING INDEX GSU.I_PRINCIPALS_OBJID
  ENABLE VALIDATE);