--DROP USER GSU CASCADE;

CREATE USER GSU
  IDENTIFIED BY GSU
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for GSU
  GRANT CONNECT TO GSU;
  GRANT RESOURCE TO GSU;
  ALTER USER GSU DEFAULT ROLE ALL;
  -- 1 System Privilege for GSU
  GRANT UNLIMITED TABLESPACE TO GSU;